"""Interactive ``voxd setup`` — config + sway snippet generator.

This subcommand is **pure file editing**. It never spawns the daemon. The user
runs ``voxd setup`` once to:

1. Prompt for an OpenRouter API key (echo-hidden via :func:`getpass.getpass`)
   and persist it to ``$XDG_CONFIG_HOME/voxd/config.toml`` at mode ``0600``.
   An existing non-empty key is kept unless the user confirms an overwrite.
2. Drop a self-contained sway snippet at
   ``~/.config/sway/config.d/voxd.conf`` containing:

       exec voxd
       bindsym Ctrl+Alt+Space exec pkill -USR2 voxd

3. Ensure the user's main sway config (``~/.config/sway/config``, or the XDG
   equivalent) sources ``config.d/*`` via the canonical
   ``include ~/.config/sway/config.d/*`` directive — added exactly once.
4. Print restart instructions (``swaymsg reload`` + ``pkill voxd && voxd``).
   Restarting the daemon is the user's responsibility; we never do it.

Idempotence: a second run with the same inputs is a no-op on disk. The sway
snippet is only rewritten when its content differs; the include line is added
only when absent.
"""

from __future__ import annotations

import getpass
import os
from dataclasses import replace
from pathlib import Path

from voxd import config as cfg_module

# ---------------------------------------------------------------------------
# Sway snippet template — exact content the plan's tests assert on.
# ---------------------------------------------------------------------------

_SWAY_SNIPPET = """# Generated by `voxd setup` — safe to edit.
exec voxd
bindsym Ctrl+Alt+Space exec pkill -USR2 voxd
"""

_INCLUDE_LINE = "include ~/.config/sway/config.d/*"

_NEW_SWAY_MAIN = f"""# Created by `voxd setup` — minimal stub.
# Add your own sway config above this line; the include must stay last so
# per-app drop-ins (like voxd) can override earlier settings.
{_INCLUDE_LINE}
"""

# Path to the distro-provided sway config (Fedora, Debian, Arch all ship one).
# Exposed as a module-level constant so tests can monkey-patch it.
_SYSTEM_DEFAULT_PATH: Path = Path("/etc/sway/config")

_COPIED_HEADER = """\
# Copied from /etc/sway/config by `voxd setup` — edit to your liking.
# The include directive at the bottom of this file already loads
# ~/.config/sway/config.d/*.conf (including voxd.conf), so a `swaymsg reload`
# picks up changes there without further edits here.
"""


# ---------------------------------------------------------------------------
# Path helpers
# ---------------------------------------------------------------------------


def _sway_dir() -> Path:
    """Return the directory housing the user's sway config files.

    Sway honours ``$XDG_CONFIG_HOME`` like every well-behaved freedesktop tool,
    falling back to ``~/.config``. We mirror :func:`voxd.config.default_path`'s
    logic so both files land in the same XDG root.
    """
    xdg = os.environ.get("XDG_CONFIG_HOME")
    base = Path(xdg) if xdg else Path.home() / ".config"
    return base / "sway"


def _sway_main_config() -> Path:
    """Path to ``~/.config/sway/config`` (or its XDG equivalent)."""
    return _sway_dir() / "config"


def _sway_snippet_path() -> Path:
    """Path to the voxd-owned snippet inside ``sway/config.d/``."""
    return _sway_dir() / "config.d" / "voxd.conf"


# ---------------------------------------------------------------------------
# Prompts
# ---------------------------------------------------------------------------


def _confirm(prompt: str, *, default: bool = False) -> bool:
    """Yes/No prompt with a default answer. Empty input returns ``default``.

    Accepts ``y``/``yes`` (case-insensitive) as Yes; anything else is No.
    """
    suffix = " [y/N] " if not default else " [Y/n] "
    answer = input(prompt + suffix).strip().lower()
    if not answer:
        return default
    return answer in {"y", "yes"}


def _prompt_api_key(existing: str) -> str:
    """Return the API key to persist.

    If a non-empty ``existing`` key is already on disk we ask the user before
    asking for a new one — that way someone re-running ``voxd setup`` after a
    sway tweak doesn't accidentally wipe their key by hitting Enter on the
    getpass prompt.
    """
    if existing:
        masked = existing[:8] + "…" if len(existing) > 8 else "(set)"
        if not _confirm(
            f"Existing API key found ({masked}). Replace?", default=False
        ):
            return existing
    return getpass.getpass("OpenRouter API key (sk-or-v1-...): ").strip()


# ---------------------------------------------------------------------------
# File operations — each is a "write only if different" helper.
# ---------------------------------------------------------------------------


def _write_if_different(path: Path, content: str, *, mode: int = 0o644) -> bool:
    """Write ``content`` to ``path`` only if the current content differs.

    Returns ``True`` if a write happened. The parent directory is created
    with mode ``0755`` (default umask) when missing.
    """
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    os.chmod(path, mode)
    return True


def _ensure_include_line(main_config: Path) -> str:
    """Make sure ``main_config`` contains the ``include`` directive.

    Returns a short status string used to shape the final user-facing
    message. Idempotent: a file that already contains the directive is
    left untouched.

    Possible return values:

    - ``"created-from-default"`` — ``main_config`` did not exist and we copied
      the distro-provided ``/etc/sway/config`` verbatim (with a voxd header).
      Crucially we do NOT append our own ``include`` line in this case: the
      system default already wires up ``config.d`` (e.g. Fedora's
      ``layered-include``), and short-circuiting that would drop user-visible
      defaults (workspace bindings, etc.).
    - ``"created"`` — ``main_config`` did not exist and no system default was
      available, so we wrote a minimal stub containing just the include line.
    - ``"added"`` — ``main_config`` existed without the include line; we
      appended it.
    - ``"present"`` — ``main_config`` already wires up ``config.d`` (either
      via the canonical line or an equivalent like ``layered-include``); we
      did nothing.
    """
    if not main_config.exists():
        main_config.parent.mkdir(parents=True, exist_ok=True)
        if _SYSTEM_DEFAULT_PATH.exists():
            # Preserve the distro defaults (bindings, layered-include, etc.)
            # by copying them into the user's config rather than masking them
            # with a one-line stub.
            system_body = _SYSTEM_DEFAULT_PATH.read_text(encoding="utf-8")
            main_config.write_text(
                _COPIED_HEADER + "\n" + system_body, encoding="utf-8"
            )
            os.chmod(main_config, 0o644)
            return "created-from-default"
        main_config.write_text(_NEW_SWAY_MAIN, encoding="utf-8")
        os.chmod(main_config, 0o644)
        return "created"

    body = main_config.read_text(encoding="utf-8")
    # Match the canonical line; also tolerate the user having added their own
    # equivalent (e.g. an absolute path or `layered-include`) — leave their
    # file alone if so.
    if _INCLUDE_LINE in body:
        return "present"
    if "include " in body and "config.d" in body:
        # User already wired up config.d differently; respect their choice.
        return "present"

    suffix = "" if body.endswith("\n") else "\n"
    main_config.write_text(body + suffix + _INCLUDE_LINE + "\n", encoding="utf-8")
    return "added"


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main() -> int:
    """Run the interactive setup. Returns ``0`` on success.

    The function is split into three concerns and reports progress for each
    so the user can see what changed on disk. Errors propagate (we don't
    swallow them) — the CLI dispatcher's exit code reflects the failure.
    """
    config_path = cfg_module.default_path()
    existing_cfg = cfg_module.load(config_path)

    api_key = _prompt_api_key(existing_cfg.openrouter.api_key)
    new_cfg = replace(
        existing_cfg,
        openrouter=replace(existing_cfg.openrouter, api_key=api_key),
    )
    cfg_module.save(new_cfg, config_path)

    snippet_path = _sway_snippet_path()
    snippet_written = _write_if_different(snippet_path, _SWAY_SNIPPET, mode=0o644)

    main_status = _ensure_include_line(_sway_main_config())

    _print_summary(
        config_path=config_path,
        snippet_path=snippet_path,
        snippet_written=snippet_written,
        main_config=_sway_main_config(),
        main_status=main_status,
    )
    return 0


def _print_summary(
    *,
    config_path: Path,
    snippet_path: Path,
    snippet_written: bool,
    main_config: Path,
    main_status: str,
) -> None:
    """Print the post-setup status block and restart instructions.

    Centralised here so :func:`main` reads as a sequence of high-level steps;
    the exact phrasing is tested by ``test_setup_prints_final_message``.
    """
    snippet_note = "written" if snippet_written else "unchanged"
    main_note = {
        "added": "include line added",
        "present": "include line already present",
        "created": "created (minimal stub)",
        "created-from-default": "created (copied from /etc/sway/config)",
    }[main_status]

    print(f"  config:  {config_path}")
    print(f"  sway snippet:  {snippet_path} ({snippet_note})")
    print(f"  sway main:  {main_config} ({main_note})")
    print()
    print("To activate, run:")
    print("  swaymsg reload                  # picks up the new bindsym")
    print("  pkill voxd && voxd &            # (re)start the daemon")
    print()
    print("Then toggle recording with Ctrl+Alt+Space.")


__all__ = ["main"]
